### ISSUE TITLE
VUE人事

### ISSUE THREAD

**Issue by tenwives** [20593/TONUSDT#2]

**Comment by lijiaming-ton** [comment]
https://github.com/SYongheng/ihr_server
是这个，
前端地址：
[git@github.com:SYongheng/ihr_vue.git](https://github.com/SYongheng/ihr_server/blob/master)

部署：
参考目录下的"用户手册"

配置：
ihr_server\src\main\resources目录下的application.properties中
@20593

**Comment by lijiaming-ton** [comment]
https://github.com/SYongheng/ihr_vue
前端的代码
